// This file will be auto-generated by Supabase CLI when properly configured
// For now, we'll define the types manually based on our schema

export interface Database {
  public: {
    Tables: {
      translations: {
        Row: {
          id: string;
          key: string;
          language: 'en' | 'ru' | 'am';
          value: string;
          category: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          language: 'en' | 'ru' | 'am';
          value: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          language?: 'en' | 'ru' | 'am';
          value?: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}

export type Translation = Database['public']['Tables']['translations']['Row'];
export type TranslationInsert = Database['public']['Tables']['translations']['Insert'];
export type TranslationUpdate = Database['public']['Tables']['translations']['Update'];
