// This file will be auto-generated by Supabase CLI when properly configured
// For now, we'll define the types manually based on our schema

export interface Database {
  public: {
    Tables: {
      translations: {
        Row: {
          id: string;
          key: string;
          language: 'en' | 'ru' | 'am';
          value: string;
          category: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          language: 'en' | 'ru' | 'am';
          value: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          language?: 'en' | 'ru' | 'am';
          value?: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          excerpt: string;
          content: string | null;
          image: string | null;
          read_time: string;
          published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          excerpt: string;
          content?: string | null;
          image?: string | null;
          read_time: string;
          published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          excerpt?: string;
          content?: string | null;
          image?: string | null;
          read_time?: string;
          published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      blog_post_translations: {
        Row: {
          id: string;
          blog_post_id: string;
          language: 'en' | 'ru' | 'am';
          title: string;
          excerpt: string;
          content: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          blog_post_id: string;
          language: 'en' | 'ru' | 'am';
          title: string;
          excerpt: string;
          content?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          blog_post_id?: string;
          language?: 'en' | 'ru' | 'am';
          title?: string;
          excerpt?: string;
          content?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          title: string;
          description: string;
          image: string | null;
          tags: string[];
          live_url: string | null;
          github_url: string | null;
          order_index: number;
          featured: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          image?: string | null;
          tags?: string[];
          live_url?: string | null;
          github_url?: string | null;
          order_index?: number;
          featured?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          image?: string | null;
          tags?: string[];
          live_url?: string | null;
          github_url?: string | null;
          order_index?: number;
          featured?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      contact_submissions: {
        Row: {
          id: string;
          from_name: string;
          from_email: string;
          message: string;
          status: 'new' | 'read' | 'replied' | 'archived';
          created_at: string;
        };
        Insert: {
          id?: string;
          from_name: string;
          from_email: string;
          message: string;
          status?: 'new' | 'read' | 'replied' | 'archived';
          created_at?: string;
        };
        Update: {
          id?: string;
          from_name?: string;
          from_email?: string;
          message?: string;
          status?: 'new' | 'read' | 'replied' | 'archived';
          created_at?: string;
        };
      };
      experiences: {
        Row: {
          id: string;
          role: string;
          company: string;
          period: string;
          description: string;
          achievements: string[];
          order_index: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          role: string;
          company: string;
          period: string;
          description: string;
          achievements?: string[];
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: string;
          company?: string;
          period?: string;
          description?: string;
          achievements?: string[];
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      education: {
        Row: {
          id: string;
          degree: string;
          school: string;
          year: string;
          description: string;
          order_index: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          degree: string;
          school: string;
          year: string;
          description: string;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          degree?: string;
          school?: string;
          year?: string;
          description?: string;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      technologies: {
        Row: {
          id: string;
          slug: string;
          language: 'en' | 'ru' | 'am';
          title: string;
          description: string;
          category: string;
          level: number;
          icon_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          language: 'en' | 'ru' | 'am';
          title: string;
          description: string;
          category: string;
          level: number;
          icon_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          language?: 'en' | 'ru' | 'am';
          title?: string;
          description?: string;
          category?: string;
          level?: number;
          icon_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      technology_details: {
        Row: {
          id: string;
          technology_id: string;
          language: 'en' | 'ru' | 'am';
          detailed_description: any;
          tags: any;
          real_world_example: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          technology_id: string;
          language: 'en' | 'ru' | 'am';
          detailed_description: any;
          tags: any;
          real_world_example: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          technology_id?: string;
          language?: 'en' | 'ru' | 'am';
          detailed_description?: any;
          tags?: any;
          real_world_example?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
        skills: {
          Row: {
            id: string;
            title: string;
            description: string;
            icon: string;
            category: string;
            level: number;
            order_index: number;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            title: string;
            description: string;
            icon: string;
            level: number;
            category?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            title?: string;
            description?: string;
            icon?: string;
            level?: number;
            category?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
        };
        education_translations: {
          Row: {
            id: string;
            education_id: string;
            language: 'en' | 'ru' | 'am';
            degree: string;
            school: string;
            year: string;
            description: string;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            education_id: string;
            language: 'en' | 'ru' | 'am';
            degree: string;
            school: string;
            year: string;
            description: string;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            education_id?: string;
            language?: 'en' | 'ru' | 'am';
            degree?: string;
            school?: string;
            year?: string;
            description?: string;
            created_at?: string;
            updated_at?: string;
          };
        };
        experience_translations: {
          Row: {
            id: string;
            experience_id: string;
            language: 'en' | 'ru' | 'am';
            role: string;
            company: string;
            period: string;
            description: string;
            achievements: string[];
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            experience_id: string;
            language: 'en' | 'ru' | 'am';
            role: string;
            company: string;
            period: string;
            description: string;
            achievements?: string[];
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            experience_id?: string;
            language?: 'en' | 'ru' | 'am';
            role?: string;
            company?: string;
            period?: string;
            description?: string;
            achievements?: string[];
            created_at?: string;
            updated_at?: string;
          };
        };
        skill_translations: {
          Row: {
            id: string;
            skill_id: string;
            language: 'en' | 'ru' | 'am';
            title: string;
            description: string;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            skill_id: string;
            language: 'en' | 'ru' | 'am';
            title: string;
            description: string;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            skill_id?: string;
            language?: 'en' | 'ru' | 'am';
            title?: string;
            description?: string;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_key_results: {
          Row: {
            id: string;
            order_index: number;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_key_result_translations: {
          Row: {
            id: string;
            key_result_id: string;
            language: 'en' | 'ru' | 'am';
            summary: string;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            key_result_id: string;
            language: 'en' | 'ru' | 'am';
            summary: string;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            key_result_id?: string;
            language?: 'en' | 'ru' | 'am';
            summary?: string;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_languages: {
          Row: {
            id: string;
            order_index: number;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_language_translations: {
          Row: {
            id: string;
            about_language_id: string;
            language: 'en' | 'ru' | 'am';
            name: string;
            level: string | null;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            about_language_id: string;
            language: 'en' | 'ru' | 'am';
            name: string;
            level?: string | null;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            about_language_id?: string;
            language?: 'en' | 'ru' | 'am';
            name?: string;
            level?: string | null;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_toolbox_items: {
          Row: {
            id: string;
            order_index: number;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_toolbox_translations: {
          Row: {
            id: string;
            toolbox_item_id: string;
            language: 'en' | 'ru' | 'am';
            label: string;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            toolbox_item_id: string;
            language: 'en' | 'ru' | 'am';
            label: string;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            toolbox_item_id?: string;
            language?: 'en' | 'ru' | 'am';
            label?: string;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_professional_journey: {
          Row: {
            id: string;
            order_index: number;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_professional_journey_translations: {
          Row: {
            id: string;
            journey_id: string;
            language: 'en' | 'ru' | 'am';
            text: string;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            journey_id: string;
            language: 'en' | 'ru' | 'am';
            text: string;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            journey_id?: string;
            language?: 'en' | 'ru' | 'am';
            text?: string;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_philosophy: {
          Row: {
            id: string;
            order_index: number;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            order_index?: number;
            created_at?: string;
            updated_at?: string;
          };
        };
        about_philosophy_translations: {
          Row: {
            id: string;
            philosophy_id: string;
            language: 'en' | 'ru' | 'am';
            text: string;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            philosophy_id: string;
            language: 'en' | 'ru' | 'am';
            text: string;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            philosophy_id?: string;
            language?: 'en' | 'ru' | 'am';
            text?: string;
            created_at?: string;
            updated_at?: string;
          };
        };
        feature_flags: {
          Row: {
            id: string;
            flag_key: string;
          content_type: 'section' | 'blog_post' | 'project';
          content_id: string | null;
          enabled: boolean;
          description: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          flag_key: string;
          content_type: 'section' | 'blog_post' | 'project';
          content_id?: string | null;
          enabled?: boolean;
          description: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          flag_key?: string;
          content_type?: 'section' | 'blog_post' | 'project';
          content_id?: string | null;
          enabled?: boolean;
          description?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}

// Translation types
export type Translation = Database['public']['Tables']['translations']['Row'];
export type TranslationInsert = Database['public']['Tables']['translations']['Insert'];
export type TranslationUpdate = Database['public']['Tables']['translations']['Update'];

// Blog post types
export type BlogPost = Database['public']['Tables']['blog_posts']['Row'];
export type BlogPostInsert = Database['public']['Tables']['blog_posts']['Insert'];
export type BlogPostUpdate = Database['public']['Tables']['blog_posts']['Update'];

// Blog post translation types
export type BlogPostTranslation = Database['public']['Tables']['blog_post_translations']['Row'];
export type BlogPostTranslationInsert = Database['public']['Tables']['blog_post_translations']['Insert'];
export type BlogPostTranslationUpdate = Database['public']['Tables']['blog_post_translations']['Update'];

// Project types
export type Project = Database['public']['Tables']['projects']['Row'];
export type ProjectInsert = Database['public']['Tables']['projects']['Insert'];
export type ProjectUpdate = Database['public']['Tables']['projects']['Update'];

// Contact submission types
export type ContactSubmission = Database['public']['Tables']['contact_submissions']['Row'];
export type ContactSubmissionInsert = Database['public']['Tables']['contact_submissions']['Insert'];
export type ContactSubmissionUpdate = Database['public']['Tables']['contact_submissions']['Update'];

// Experience types
  export type Experience = Database['public']['Tables']['experiences']['Row'];
  export type ExperienceInsert = Database['public']['Tables']['experiences']['Insert'];
  export type ExperienceUpdate = Database['public']['Tables']['experiences']['Update'];
  export type ExperienceTranslation = Database['public']['Tables']['experience_translations']['Row'];
  export type ExperienceTranslationInsert = Database['public']['Tables']['experience_translations']['Insert'];
  export type ExperienceTranslationUpdate = Database['public']['Tables']['experience_translations']['Update'];
  
  // Education types
  export type Education = Database['public']['Tables']['education']['Row'];
  export type EducationInsert = Database['public']['Tables']['education']['Insert'];
  export type EducationUpdate = Database['public']['Tables']['education']['Update'];
  export type EducationTranslation = Database['public']['Tables']['education_translations']['Row'];
  export type EducationTranslationInsert = Database['public']['Tables']['education_translations']['Insert'];
  export type EducationTranslationUpdate = Database['public']['Tables']['education_translations']['Update'];
  
  // Skill types
  export type Skill = Database['public']['Tables']['skills']['Row'];
  export type SkillInsert = Database['public']['Tables']['skills']['Insert'];
  export type SkillUpdate = Database['public']['Tables']['skills']['Update'];
  export type SkillTranslation = Database['public']['Tables']['skill_translations']['Row'];
  export type SkillTranslationInsert = Database['public']['Tables']['skill_translations']['Insert'];
  export type SkillTranslationUpdate = Database['public']['Tables']['skill_translations']['Update'];

// Technology types
export type Technology = Database['public']['Tables']['technologies']['Row'];
export type TechnologyInsert = Database['public']['Tables']['technologies']['Insert'];
export type TechnologyUpdate = Database['public']['Tables']['technologies']['Update'];

// Technology detail types
export type TechnologyDetail = Database['public']['Tables']['technology_details']['Row'];
export type TechnologyDetailInsert = Database['public']['Tables']['technology_details']['Insert'];
export type TechnologyDetailUpdate = Database['public']['Tables']['technology_details']['Update'];

// Feature flag types
export type FeatureFlag = Database['public']['Tables']['feature_flags']['Row'];
export type FeatureFlagInsert = Database['public']['Tables']['feature_flags']['Insert'];
export type FeatureFlagUpdate = Database['public']['Tables']['feature_flags']['Update'];
